### ISSUE TITLE
조아라 파싱 방법

### ISSUE THREAD

**Issue by DevKiHyun** [Beomi/dailyparser#3]
조아라 파싱할때 굳이 사용자의 계정으로 접속하는
이유가 무엇인가요?
코드를 보니 auth  변수에 로그인을 post 하는 것까지 봤는데
그 뒤로 auth 를 사용하는 것 같지가 않습니다.
이것은 어디에 필요한가요?

**Comment by Beomi** [comment]
auth은 사용하지 않는 변수입니다 :)
로그인이 되었는지 확인은 가능하지만, 그 줄이 있는 이유는 s.post(로그인URL)을 통해서 조아라에 로그인을 해주고 그 세션을 `s`에 유지시켜주는 것이기 때문입니다.
즉, auth라는 변수에 굳이 할당해줄 이유 없이 `s.post()`만 쓰고 진행하셔도 됩니다.

**Comment by DevKiHyun** [comment]
로그인은 사실상 파싱하는데는 상관이 없다면
s.post()로 지정하고나 auth 부분을 없앤후
계정 입력부분은 공백으로 진행해도 되는거죠?

**Comment by Beomi** [comment]
네. 로그인이 필요없는 경우에 한에서입니다.
